name = "xes-software/xes-software"
version = "0.0.0"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'xes-software/xes-software'"

[repository]
user = "xes-software"
project = "xes-software"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.6"
source = "github"

[config]
